version: '3.8'

services:
  frontend:
    build:
      context: ./viceri-todo-app
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./viceri-todo-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
